### PR TITLE
33 set upenv celest find a way to work with celest

### PR DESCRIPTION
**Pull request by COTHSC**
# Description

Replaced wfntp submodule, wfntp is now part of our codebase, added how to's for celeST and WF_NTP

### CODE REVIEW

**Comment by madvid** [comment]
First of all, there is a really big problem.
We should never have 1552 files changed in in a PR.
image

**Comment by madvid** [comment]
the hidden file gitmodules has not been modified/removed

**Comment by madvid** [comment]
image

* What is `Sample02` ?
* What is `Xerces-J-bin.2.12.2` ? It is too big / to many files in it. Instead describe how to get it and why do we need it ?
* I removed `__MACOSX`
* what is `data` ? Is it related to the associated issue of the PR ?
* what is `octave_measures_backup` ? Is it related to the associated issue of the PR ?
* What is `octave-workspace` ? why is it here ? is it related to the issue ?

**Review by madvid — CHANGES_REQUESTED** [review]
It seems there are files unrelated to the issues. Plus too much junk files and files and directory in the PR without any explanations of its uses

**Comment by COTHSC** [comment]
> image

* What is `Sample02` ?
Its a small sample that can be used to run CeleST, I removed it now that the information on where to get sample data is in the howto

* What is `Xerces-J-bin.2.12.2` ? It is too big / to many files in it. Instead describe how to get it and why do we need it ?
Its a java library needed to read and write to xml files, if I remove it, the user will need to change the path in the CeleST file, I will document this in the setup.md file

* I removed `__MACOSX`
oops, my bad!

* what is `data` ? Is it related to the associated issue of the PR ?
Its the directory where CeleST outputs, if it doesn't exist, it will be created by CeleST, I think it makes sense for it to stay so measures made by anyone can be loaded and visualized by others

* what is `octave_measures_backup` ? Is it related to the associated issue of the PR ?
Yes, We will need it to compare to other measures, made in matlab etc.

* What is `octave-workspace` ? why is it here ? is it related to the issue ?
I had misunderstood its usefullness, it was generated during a crash and has been removed

**Comment by madvid** [comment]
Tests are failing due to WF NTP source code which does not comply with our code standard

**Pull request merged**
